### ISSUE TITLE
recorder_transformer multilayer json

### ISSUE THREAD

**Issue by alanyee** [fluent/fluentd-docs#237]
http://docs.fluentd.org/articles/filter_record_transformer does not clearly stated how to transform a json into a multilayer json.

For instance, let's say I have
```
{
  "a":"a",
  "b":"b",
  "c":"c"
}
```
And I want to filter it such that I have
```
{
  "abc": 
  {
    "a":"a",
    "b":"b",
    "c":"c"
  }
}
```
So do I do this with recorder_transformer? And if I can, the instructions should be written in the docs.

**Comment by sonots** [comment]
Your example can be achieved by:

```
  <filter *.*>
    @type record_transformer
    enable_ruby yes
    auto_typecast yes
    <record>
      abc ${record}
    </record>
  </filter>
```

If you want to restrict keys or change key names, it must be written like:

```
  <filter *.*>
    @type record_transformer
    enable_ruby yes
    auto_typecast yes
    <record>
      abc ${{'foo'=>record['a']}}
    </record>
  </filter>
```

This produces

```
{
  "abc": 
  {
    "foo":"a"
  }
}
```

This is not supported by `enable_ruby no` version.

I may want to support json path notation in the future like:

```
  <filter *.*>
    @type record_transformer
    enable_ruby yes
    auto_typecast yes
    <record>
      $.abc.foo ${record['a']}
    </record>
  </filter>
```

so that nested hash support works even with `enable_ruby no`.
Please wait writing about this on docs. I am not deciding yet.

**Comment by alanyee** [comment]
Then how would I create
```
{
  "ab": 
  {
    "a":"a",
    "b":"b",
  }
}
```
given the record:
```
{
  "a":"a",
  "b":"b",
  "c":"c"
}
```

**Comment by sonots** [comment]
It is just a ruby question, you can write as:

```
ab ${{'a'=>record['a'],'b'=>record['b']}}
```
